### ISSUE TITLE
Are you open to some new classes?

### ISSUE THREAD

**Issue by himedlooff** [cfpb/DOCter#8]
There are a few instances of directly styling all elements when you should probably use a class for example:

``` CSS
section:before {
    display: block; 
    content: ""; 
    height: 60px; 
    margin: -60px 0 0; 
}
```

...

``` CSS
header {
    width: 100%;
    border-top: 4px solid #2CB34A;
    border-bottom: 1px solid #BABBBD;
    background-color: #fff;
    position: fixed;
    top: 0;
    z-index: 99999;
    height: 3.625em;
}
```

Are you open to swapping some of these for class names?
